### ISSUE TITLE
Optimize building

### ISSUE THREAD

**Issue by Justme0** [mchalupa/dg#106]
In tools/CMakeLists.txt, I recommand using the following script to get the definition `GIT_VERSION`, because I want to build the project out-of-source : )
```cmake
execute_process(COMMAND git rev-parse --short=8 HEAD OUTPUT_VARIABLE GITVERSION)
string(REGEX REPLACE "\n$" "" GITVERSION "${GITVERSION}")
add_definitions(-DGIT_VERSION="${GITVERSION}")
```

**Comment by mchalupa** [comment]
Yeah, sure, looks good. Could you make a pull-request, please?

Thanks

**Comment by twang15** [comment]
Hey Marek,

I am using llvmslicer. Except llvmslicer is based on cfg and dg is based on
pdg, what are the other major differences between dg and llvmslicer ? Does
dg generate smaller slice ?

Thanks a lot.

**Comment by mchalupa** [comment]
Hi,

You mean LLVMSlicer? (https://github.com/jirislaby/LLVMSlicer). The major difference is that dg has more precise and sound analyses (which can lead to smaller slices). The slicing algorithm itself slices more or less the same, since I haven't implemented the two-pass algorithm of Horwitz nor any other more precise version (e.g. specialization slicing) yet. Actually, dg was designed as a replacement for LLVMSlicer in the tool Symbiotic (https://github.com/staticafi/symbiotic). You can find more detailed information about dg here: http://is.muni.cz/th/396236/fi_m/thesis.pdf

P.S. for any further discussion please start a new issue or send me an e-mail, this issue is about something else
