### ISSUE TITLE
Not all sliced programs are executable

### ISSUE THREAD

**Issue by mr-ma** [mchalupa/dg#128]
Not sure whether this is a known problem or a feature request.
Assume the following input program:
```
int a=0;
void dcs(int i){
    //do nothing just a dummy call site
}
int main(){
    int b=5;
    a+=b;
    dcs(a);
    return 0;
}
```
For that example if I slice for "dcs", then the .sliced file cannot be executed (say using lli)  because dcs function cannot be resolved. Particularly, lli throws "LLVM ERROR: Program used external function 'dcs' which could not be resolved".

I don't think that dcs call should be added to the sliced program as it does not write anything to variable a, so dg does a good job by removing it from the bitcode. However, it somehow fails to remove the call (call site) to dcs. Removing the call should fix this problem.

What do you think?

**Comment by mchalupa** [comment]
Hi,

the fact that we keep this particullar call-site in the slice is intentional. It is because we use dependence graphs to perform slicing where the procedure marks also the slicing criterion's node (which is the call-site). And in our use-case we also want this behavior, since we usually slice w.r.t `__assert_fail`, which are calls that we want to keep.

Anyway, we can add a switch to force your desired behavior, the only thing that is needed is to not initially mark the slicing criterion's node, but only its predecessors in the dependence graph.

P.S. a fast workaround would be to link an empty body for the slicing criterion using `llvm-link` after slicing.

**Comment by mr-ma** [comment]
Hi,
Thanks for the comment. Having a switch to exclude the call-site seems like a great idea.
Let's turn this to a feature request then.

Thanks a lot,
M

**Comment by mchalupa** [comment]
Sorry for such a long delay, I kind of forgot about this issue.
