### ISSUE TITLE
Conditional memory allocation

### ISSUE THREAD

**Issue by thierry-tct** [mchalupa/dg#136]
Hello,
in the code bellow, `llvm-dg-dump` will complain with __`WARNING: a call via a function pointer, but the points-to is empty`__(in the `main` function, the memory is allocated if the poiter is null):
``` C
#include <stdlib.h>

int x;

 void foo(int a) {
         x = 1;
 }

 void foo2(int a) {
         x = 2;
 }

 struct T {
      void (*f) (int c);
      int c;
 };

 int main(void) {
         int a = 1;
         struct T *pt = NULL;
         if (!pt)    // can also be: if(numElem==0), where numElem is a variable keeping the legth of pt
             pt = (struct T*) malloc (sizeof(struct T));
         pt[0].f = (a == 1 ? foo : foo2);
         pt[0].f(a);
         //test_assert(x == 1);
         return 0;
}
```
Is it possible is the analysis to consider in this case that the instructions following the `if` and `malloc` cannot be executed with `pt` unallocated?

_P.S.:_ Please what can be the cause of the following: 
1. __Function pointer call with no compatible pointer__
2. __WARNING: Non-0 memset:   call void @llvm.memset.p0i8.i64(...)__

Thanks

**Comment by mchalupa** [comment]
Hi,

I guess you used the flow-sensitive analysis, because I do not get such result with flow-insensitive?

> Is it possible is the analysis to consider in this case that the instructions following the if and malloc cannot be executed with pt unallocated?

I don't think so, the analysis does not make any assumptions about the branches, it must assume that both are possible. I think its a bug in the analysis. Maybe it is coupled with the #137.

> P.S.: Please what can be the cause of the following:
>  1. Function pointer call with no compatible pointer

Since the pointer analysis is over-approximation, it may happen that the points-to set of a function pointer contains e.g. pointers to an integer. This can be reached quite easily with a function that has a variadic number of arguments: dg simply merges all the pointers into one node that represents "all pointers that may be passed through va_list". For example:
```C
foo(int x, ...) {
 ...
  y = va_arg(args, int *)
 ...
}

foo(3, &a, &b, &c);
// y will points to {a ,b, c}
```

Because of this fact, the dg makes (possibly incorrect) assumption that a function called via a function pointer must be compatible with the call, that is that when you call `f` in this code snippet:
```
void foo(int);
int foo2(void);

(void) (*f)(int) = ...;
f(5);
```

then f may not point to `foo2`, because the function type is not compatible with the function pointer's type. The warning in your question is raised whenever the analysis found a call via a function pointer,
but no suitable function is in the points-to set (pointers are incompatible with the function pointer).

>  2. WARNING: Non-0 memset: call void @llvm.memset.p0i8.i64(...)

This warning is raised when a pointer subgraph builds a `llvm.memset` call and this call does not zero-out the memory, but sets it to some other value instead. Setting a pointer using a memset to such a value would yield unknown pointer. Such a memset can be present in the pointer subgraph because of inttoptr/ptrtoint instructions.

**Comment by thierry-tct** [comment]
Thanks much for the reply.
Yes I used flow-sensitive. It works with flow-insensitive.

**Comment by mchalupa** [comment]
This issue is still not solved, let's keep it open until we know if it is the same as #137 or until we solve it.

**Comment by thierry-tct** [comment]
Alright, i see.

**Comment by mchalupa** [comment]
OK, it look like it was the #137 problem, so I'm closing this issue. Re-open if needed.

**Comment by thierry-tct** [comment]
Algright, thanks
