### ISSUE TITLE
About Secondary Slicing Criteria

### ISSUE THREAD

**Issue by Tigerly** [mchalupa/dg#285]
Hello,

I'm curious about "SecondarySlicingCriteria".

Would it be possible to explain a little bit, e.g.:
what is the secondary slicing criteria?
what is the application scenario of it?
how to use it?

Thanks in advance!

**Comment by mchalupa** [comment]
Hi,

secondary slicing critaria in llvm-slicer is a way how to say "make this node slicing criterion if it is on a path to the original slicing criterion (and possibly satisfies also some other conditions)". It has no additional expressive power, you could use dependence edges instead. The effect is that it just saves edges in the graph and allows you to handle some situation more easily (or even ellegantly, I would say). We use it, for example, to handle assumptions when we use slicing before finding bugs in programs (https://github.com/staticafi/symbiotic). Consider you have this code:

```C
x = nondet();
assume(x > 10);
assert(x != 100);
```

You do not want to slice away the assumption, so you can add some extra edges to the dependence graph (or transform the assumption to `if (!cond) exit` which you may not want to do for various reasons; or you can pretend that the assumption writes to the variable `x`, but that is not simple when using LLVM as the `assume` function takes bool and you would need to somehow backtrack what variables were used in the condition).
So, instead, we say that `assume` is secondary slicing criterion and if the slicing criterion is `assert`, then this call to `assume` is also marked as a slicing criterion since it is on a path to the `assert` and it is left in the slice (with its dependencies).

You can specify secondary slicing criteria using `-2c` switch (check the `-help`).

**Comment by mchalupa** [comment]
> make this node

**Comment by mchalupa** [comment]
This question has been reflected in the docs, so I am closing this issue.
