### ISSUE TITLE
[question] about the slicing example -- fact.c

### ISSUE THREAD

**Issue by Tigerly** [mchalupa/dg#286]
Hello,

I tried the given slicing example of fact.c (https://github.com/mchalupa/dg#example), and I found two problems:

**1. after slicing, the sliced function `__assert_fail` still there:**

I slice it by using command ------ `./llvm-slicer -c __assert_fail fact.bc`, and compare the IR code before and after slicing. And I found that the `__assert_fail` still there after I slice it.
So, I was wondering:
**a) is it correct behavior?
b) after slicing, can I remove the sliced function's callsite (`call void @__assert_fail(...)`) safely without any dependency error?**

**2. cannot directly compile the sliced file:**

I slice it by using command ------ `./llvm-slicer -c __assert_fail fact.bc`
and get the file ------ `fact.sliced`
Then, I try to directly compile it to executable: `clang fact.sliced -o xx`
It complains: 
```
fact.sliced: file not recognized: File format not recognized
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```  
However, after I convert it to readable IR file by using command ------` llvm-dis fact.sliced -o fact.sliced.ll
`
Then, I can compile the `fact.sliced.ll` to executable successfully and it can execute well.

**I was wondering whether it is correct behavior?**

Thanks in advance!

**Comment by mchalupa** [comment]
Hi,
> 1. after slicing, the sliced function __assert_fail still there

a) yes, it is on purpose
b) yes, you can remove the slicing criteria  (if it is not dependent on itself) by using the `-remove-slicing-criteria` option

> 2. cannot directly compile the sliced file

The problem is caused by the suffix `.sliced`, because clang uses suffixes to find out what to do. If you rename the file to end with `.bc`, then it will work (and that is why `llvm-dis` worked, because it renamed the file to have the suffix `.ll`). You can use `-o` option to give the output from the slicer a name.
