### ISSUE TITLE
Can DG suppport Windows?

### ISSUE THREAD

**Issue by ChaosLee03** [mchalupa/dg#315]

**Comment by mchalupa** [comment]
I do not know, you must try ;) I am not aware of any non-portable features in the code, however, there may probably be some.

**Comment by ChaosLee03** [comment]
Thank you for your time first, I tried again but failed. I have the same problem with #196 ,I'll really appreaciate it if you can offer some help. @mchalupa

**Comment by mchalupa** [comment]
Since I do not have Windows where I could try to build dg, the only thing I can do is to suggest to search the internet for how to properly link to LLVM libraries on Windows (if you have exactly the same problems as in #196). Try to check out e.g., this https://stackoverflow.com/questions/60024155/fail-to-compile-pass-to-dll-on-windows (there's no answer yet, but it can be a good starting point).

**Comment by mchalupa** [comment]
@ChaosLee03: did you succeed compiling dg on Windows?

**Comment by ChaosLee03** [comment]
> @ChaosLee03: did you succeed compiling dg on Windows?

No, I compliling in the  Windows Subsystem for Linux.
