### ISSUE TITLE
Value relations anlaysis hits an assert

### ISSUE THREAD

**Issue by mchalupa** [mchalupa/dg#365]
Value relation analysis fails on this bitcode:
[code.zip](https://github.com/mchalupa/dg/files/5582866/code.zip)

```
llvm-vr-dump: /home/marek/src/symbiotic/dg/include/dg/llvm/ValueRelations/ValueRelations.h:768: void dg::vr::ValueRelations::setEqual(dg::vr::EqualityBucket*, dg::vr::EqualityBucket*): Assertion `!hasConflictingRelation(newBucketPtr, oldBucketPtr, Relation::EQ)' failed.
[1]    183375 abort (core dumped)  build-10.0.1/tools/llvm-vr-dump 
```

**Comment by mchalupa** [comment]
@GiraffeReversed, do you know where is the problem?

**Comment by GiraffeReversed** [comment]
Unfortunately, I get a parse error when attempting to run the analysis with any of the codes. Not sure what the cause might be... (using llvm 6.0)

Failed parsing 'code-pr.bc' file:
tools/llvm-vr-dump: code-pr.bc: error: Unknown attribute kind (61) (Producer: 'LLVM10.0.1' Reader: 'LLVM 6.0.0')

Failed parsing 'code-pr.ll' file:
tools/llvm-vr-dump: code-pr.ll:1600:44: error: expected ')' at end of argument list
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #3
                                           ^

Nevertheless, I believe I know what the problem is and it should be quite easy to fix (I encountered it in one of the files you sent me before).

**Comment by mchalupa** [comment]
> Unfortunately, I get a parse error when attempting to run the analysis with any of the codes. Not sure what the cause might be... 

The cause is that the bitcode is LLVM 10

**Comment by mchalupa** [comment]
Is the fix hard? Would you be able to make it quickly?

**Comment by GiraffeReversed** [comment]
Yes, this solves it on my machine :)

**Comment by mchalupa** [comment]
I think this should be resolved now. We'll re-open it in case we'll find out it is not.
